INSERT INTO `s_core_documents_box` (`id`, `documentID`, `name`, `style`, `value`) VALUES
(1,	1,	'Body',	'width:100%;\r\nfont-family: Verdana, Arial, Helvetica, sans-serif;\r\nfont-size:11px;',	''),
(2,	1,	'Logo',	'height: 20mm;\r\nwidth: 90mm;\r\nmargin-bottom:5mm;',	'<p><img src=\"http://www.shopware.de/logo/logo.png\" alt=\"\" /></p>'),
(3,	1,	'Header_Recipient',	'',	''),
(4,	1,	'Header',	'height: 60mm;',	''),
(5,	1,	'Header_Sender',	'',	'<p>Demo GmbH - Stra&szlig;e 3 - 00000 Musterstadt</p>'),
(6,	1,	'Header_Box_Left',	'width: 120mm;\r\nheight:60mm;\r\nfloat:left;',	''),
(7,	1,	'Header_Box_Right',	'width: 45mm;\r\nheight: 60mm;\r\nfloat:left;\r\nmargin-top:-20px;\r\nmargin-left:5px;',	'<p><strong>Demo GmbH </strong><br /> Max Mustermann<br /> Stra&szlig;e 3<br /> 00000 Musterstadt<br /> Fon: 01234 / 56789<br /> Fax: 01234 / 			56780<br />info@demo.de<br />www.demo.de</p>'),
(8,	1,	'Header_Box_Bottom',	'font-size:14px;\r\nheight: 10mm;',	''),
(9,	1,	'Content',	'height: 65mm;\r\nwidth: 170mm;',	''),
(10,	1,	'Td',	'white-space:nowrap;\r\npadding: 5px 0;',	''),
(11,	1,	'Td_Name',	'white-space:normal;',	''),
(12,	1,	'Td_Line',	'border-bottom: 1px solid #999;\r\nheight: 0px;',	''),
(13,	1,	'Td_Head',	'border-bottom:1px solid #000;',	''),
(14,	1,	'Footer',	'width: 170mm;\r\nposition:fixed;\r\nbottom:-20mm;\r\nheight: 15mm;',	'<table style=\"vertical-align: top;\" width=\"100%\" border=\"0\">\r\n<tbody>\r\n<tr valign=\"top\">\r\n<td style=\"width: 25%;\">\r\n<p><span style=\"font-size: xx-small;\">Demo GmbH</span></p>\r\n<p><span style=\"font-size: xx-small;\">Steuer-Nr <br />UST-ID: <br />Finanzamt </span><span style=\"font-size: xx-small;\">Musterstadt</span></p>\r\n</td>\r\n<td style=\"width: 25%;\">\r\n<p><span style=\"font-size: xx-small;\">Bankverbindung</span></p>\r\n<p><span style=\"font-size: xx-small;\">Sparkasse Musterstadt<br />BLZ: <br />Konto: </span></p>\r\n<span style=\"font-size: xx-small;\">aaaa<br /></span></td>\r\n<td style=\"width: 25%;\">\r\n<p><span style=\"font-size: xx-small;\">AGB<br /></span></p>\r\n<p><span style=\"font-size: xx-small;\">Gerichtsstand ist Musterstadt<br />Erf&uuml;llungsort Musterstadt<br />Gelieferte Ware bleibt bis zur vollst&auml;ndigen Bezahlung unser Eigentum</span></p>\r\n</td>\r\n<td style=\"width: 25%;\">\r\n<p><span style=\"font-size: xx-small;\">Gesch&auml;ftsf&uuml;hrer</span></p>\r\n<p><span style=\"font-size: xx-small;\">Max Mustermann</span></p>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>'),
(15,	1,	'Content_Amount',	'margin-left:90mm;',	''),
(16,	1,	'Content_Info',	'',	'<p>Die Ware bleibt bis zur vollst&auml;ndigen Bezahlung unser Eigentum</p>'),
(68,	2,	'Body',	'width:100%;\r\nfont-family: Verdana, Arial, Helvetica, sans-serif;\r\nfont-size:11px;',	''),
(69,	2,	'Logo',	'height: 20mm;\r\nwidth: 90mm;\r\nmargin-bottom:5mm;',	'<p><img src=\"http://www.shopware.de/logo/logo.png\" alt=\"\" /></p>'),
(70,	2,	'Header_Recipient',	'',	''),
(71,	2,	'Header',	'height: 60mm;',	''),
(72,	2,	'Header_Sender',	'',	'<p>Demo GmbH - Stra&szlig;e 3 - 00000 Musterstadt</p>'),
(73,	2,	'Header_Box_Left',	'width: 120mm;\r\nheight:60mm;\r\nfloat:left;',	''),
(74,	2,	'Header_Box_Right',	'width: 45mm;\r\nheight: 60mm;\r\nfloat:left;\r\nmargin-top:-20px;\r\nmargin-left:5px;',	'<p><strong>Demo GmbH </strong><br /> Max Mustermann<br /> Stra&szlig;e 3<br /> 00000 Musterstadt<br /> Fon: 01234 / 56789<br /> Fax: 01234 / 			56780<br />info@demo.de<br />www.demo.de</p>'),
(75,	2,	'Header_Box_Bottom',	'font-size:14px;\r\nheight: 10mm;',	''),
(76,	2,	'Content',	'height: 65mm;\r\nwidth: 170mm;',	''),
(77,	2,	'Td',	'white-space:nowrap;\r\npadding: 5px 0;',	''),
(78,	2,	'Td_Name',	'white-space:normal;',	''),
(79,	2,	'Td_Line',	'border-bottom: 1px solid #999;\r\nheight: 0px;',	''),
(80,	2,	'Td_Head',	'border-bottom:1px solid #000;',	''),
(81,	2,	'Footer',	'width: 170mm;\r\nposition:fixed;\r\nbottom:-20mm;\r\nheight: 15mm;',	'<table style=\"vertical-align: top;\" width=\"100%\" border=\"0\">\r\n<tbody>\r\n<tr valign=\"top\">\r\n<td style=\"width: 25%;\">\r\n<p><span style=\"font-size: xx-small;\">Demo GmbH</span></p>\r\n<p><span style=\"font-size: xx-small;\">Steuer-Nr <br />UST-ID: <br />Finanzamt </span><span style=\"font-size: xx-small;\">Musterstadt</span></p>\r\n</td>\r\n<td style=\"width: 25%;\">\r\n<p><span style=\"font-size: xx-small;\">Bankverbindung</span></p>\r\n<p><span style=\"font-size: xx-small;\">Sparkasse Musterstadt<br />BLZ: <br />Konto: </span></p>\r\n<span style=\"font-size: xx-small;\">aaaa<br /></span></td>\r\n<td style=\"width: 25%;\">\r\n<p><span style=\"font-size: xx-small;\">AGB<br /></span></p>\r\n<p><span style=\"font-size: xx-small;\">Gerichtsstand ist Musterstadt<br />Erf&uuml;llungsort Musterstadt<br />Gelieferte Ware bleibt bis zur vollst&auml;ndigen Bezahlung unser Eigentum</span></p>\r\n</td>\r\n<td style=\"width: 25%;\">\r\n<p><span style=\"font-size: xx-small;\">Gesch&auml;ftsf&uuml;hrer</span></p>\r\n<p><span style=\"font-size: xx-small;\">Max Mustermann</span></p>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>'),
(82,	2,	'Content_Amount',	'margin-left:90mm;',	''),
(83,	2,	'Content_Info',	'',	'<p>Die Ware bleibt bis zur vollst&auml;ndigen Bezahlung unser Eigentum</p>'),
(84,	3,	'Body',	'width:100%;\r\nfont-family: Verdana, Arial, Helvetica, sans-serif;\r\nfont-size:11px;',	''),
(85,	3,	'Logo',	'height: 20mm;\r\nwidth: 90mm;\r\nmargin-bottom:5mm;',	'<p><img src=\"http://www.shopware.de/logo/logo.png\" alt=\"\" /></p>'),
(86,	3,	'Header_Recipient',	'',	''),
(87,	3,	'Header',	'height: 60mm;',	''),
(88,	3,	'Header_Sender',	'',	'<p>Demo GmbH - Stra&szlig;e 3 - 00000 Musterstadt</p>'),
(89,	3,	'Header_Box_Left',	'width: 120mm;\r\nheight:60mm;\r\nfloat:left;',	''),
(90,	3,	'Header_Box_Right',	'width: 45mm;\r\nheight: 60mm;\r\nfloat:left;\r\nmargin-top:-20px;\r\nmargin-left:5px;',	'<p><strong>Demo GmbH </strong><br /> Max Mustermann<br /> Stra&szlig;e 3<br /> 00000 Musterstadt<br /> Fon: 01234 / 56789<br /> Fax: 01234 / 			56780<br />info@demo.de<br />www.demo.de</p>'),
(91,	3,	'Header_Box_Bottom',	'font-size:14px;\r\nheight: 10mm;',	''),
(92,	3,	'Content',	'height: 65mm;\r\nwidth: 170mm;',	''),
(93,	3,	'Td',	'white-space:nowrap;\r\npadding: 5px 0;',	''),
(94,	3,	'Td_Name',	'white-space:normal;',	''),
(95,	3,	'Td_Line',	'border-bottom: 1px solid #999;\r\nheight: 0px;',	''),
(96,	3,	'Td_Head',	'border-bottom:1px solid #000;',	''),
(97,	3,	'Footer',	'width: 170mm;\r\nposition:fixed;\r\nbottom:-20mm;\r\nheight: 15mm;',	'<table style=\"vertical-align: top;\" width=\"100%\" border=\"0\">\r\n<tbody>\r\n<tr valign=\"top\">\r\n<td style=\"width: 25%;\">\r\n<p><span style=\"font-size: xx-small;\">Demo GmbH</span></p>\r\n<p><span style=\"font-size: xx-small;\">Steuer-Nr <br />UST-ID: <br />Finanzamt </span><span style=\"font-size: xx-small;\">Musterstadt</span></p>\r\n</td>\r\n<td style=\"width: 25%;\">\r\n<p><span style=\"font-size: xx-small;\">Bankverbindung</span></p>\r\n<p><span style=\"font-size: xx-small;\">Sparkasse Musterstadt<br />BLZ: <br />Konto: </span></p>\r\n<span style=\"font-size: xx-small;\">aaaa<br /></span></td>\r\n<td style=\"width: 25%;\">\r\n<p><span style=\"font-size: xx-small;\">AGB<br /></span></p>\r\n<p><span style=\"font-size: xx-small;\">Gerichtsstand ist Musterstadt<br />Erf&uuml;llungsort Musterstadt<br />Gelieferte Ware bleibt bis zur vollst&auml;ndigen Bezahlung unser Eigentum</span></p>\r\n</td>\r\n<td style=\"width: 25%;\">\r\n<p><span style=\"font-size: xx-small;\">Gesch&auml;ftsf&uuml;hrer</span></p>\r\n<p><span style=\"font-size: xx-small;\">Max Mustermann</span></p>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>'),
(98,	3,	'Content_Amount',	'margin-left:90mm;',	''),
(99,	3,	'Content_Info',	'',	'<p>Die Ware bleibt bis zur vollst&auml;ndigen Bezahlung unser Eigentum</p>'),
(100,	4,	'Body',	'width:100%;\r\nfont-family: Verdana, Arial, Helvetica, sans-serif;\r\nfont-size:11px;',	''),
(101,	4,	'Logo',	'height: 20mm;\r\nwidth: 90mm;\r\nmargin-bottom:5mm;',	'<p><img src=\"http://www.shopware.de/logo/logo.png\" alt=\"\" /></p>'),
(102,	4,	'Header_Recipient',	'',	''),
(103,	4,	'Header',	'height: 60mm;',	''),
(104,	4,	'Header_Sender',	'',	'<p>Demo GmbH - Stra&szlig;e 3 - 00000 Musterstadt</p>'),
(105,	4,	'Header_Box_Left',	'width: 120mm;\r\nheight:60mm;\r\nfloat:left;',	''),
(106,	4,	'Header_Box_Right',	'width: 45mm;\r\nheight: 60mm;\r\nfloat:left;\r\nmargin-top:-20px;\r\nmargin-left:5px;',	'<p><strong>Demo GmbH </strong><br /> Max Mustermann<br /> Stra&szlig;e 3<br /> 00000 Musterstadt<br /> Fon: 01234 / 56789<br /> Fax: 01234 / 			56780<br />info@demo.de<br />www.demo.de</p>'),
(107,	4,	'Header_Box_Bottom',	'font-size:14px;\r\nheight: 10mm;',	''),
(108,	4,	'Content',	'height: 65mm;\r\nwidth: 170mm;',	''),
(109,	4,	'Td',	'white-space:nowrap;\r\npadding: 5px 0;',	''),
(110,	4,	'Td_Name',	'white-space:normal;',	''),
(111,	4,	'Td_Line',	'border-bottom: 1px solid #999;\r\nheight: 0px;',	''),
(112,	4,	'Td_Head',	'border-bottom:1px solid #000;',	''),
(113,	4,	'Footer',	'width: 170mm;\r\nposition:fixed;\r\nbottom:-20mm;\r\nheight: 15mm;',	'<table style=\"vertical-align: top;\" width=\"100%\" border=\"0\">\r\n<tbody>\r\n<tr valign=\"top\">\r\n<td style=\"width: 25%;\">\r\n<p><span style=\"font-size: xx-small;\">Demo GmbH</span></p>\r\n<p><span style=\"font-size: xx-small;\">Steuer-Nr <br />UST-ID: <br />Finanzamt </span><span style=\"font-size: xx-small;\">Musterstadt</span></p>\r\n</td>\r\n<td style=\"width: 25%;\">\r\n<p><span style=\"font-size: xx-small;\">Bankverbindung</span></p>\r\n<p><span style=\"font-size: xx-small;\">Sparkasse Musterstadt<br />BLZ: <br />Konto: </span></p>\r\n<span style=\"font-size: xx-small;\">aaaa<br /></span></td>\r\n<td style=\"width: 25%;\">\r\n<p><span style=\"font-size: xx-small;\">AGB<br /></span></p>\r\n<p><span style=\"font-size: xx-small;\">Gerichtsstand ist Musterstadt<br />Erf&uuml;llungsort Musterstadt<br />Gelieferte Ware bleibt bis zur vollst&auml;ndigen Bezahlung unser Eigentum</span></p>\r\n</td>\r\n<td style=\"width: 25%;\">\r\n<p><span style=\"font-size: xx-small;\">Gesch&auml;ftsf&uuml;hrer</span></p>\r\n<p><span style=\"font-size: xx-small;\">Max Mustermann</span></p>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>'),
(114,	4,	'Content_Amount',	'margin-left:90mm;',	''),
(115,	4,	'Content_Info',	'',	'<p>Die Ware bleibt bis zur vollst&auml;ndigen Bezahlung unser Eigentum</p>');